# Direct vs. Diffuse Light Input Parameters (`difcol.inp`)

This document describes the format for the `difcol.inp` file. This file provides wavelength-dependent data on the fraction of collimated (direct) light and the relative intensity of photons for each waveband.

**Important**: This file is only read by the model if parameter `2) Light source from model(0) or file(1)` in `amc.inp` is set to `0`.

## File Format

The structure of the `difcol.inp` file is as follows:

1.  **Number of Wavebands**: The very first value in the file must be an integer representing the total number of wavebands. This number **must** match the value specified for parameter `18) Number of wavebands` in the `amc.inp` file.

2.  **Light Fraction and Intensity**: Following the number of wavebands, the file must contain one line of data for each waveband. Each line consists of two floating-point values:
    *   **Direct Fraction**: The first value on the line is the fraction of light that is collimated (direct) for that specific waveband. This should be a value between 0.0 and 1.0.
    *   **Relative Intensity**: The second value is a weighting factor for the number of photons to be simulated at that waveband. This factor is multiplied by the total number of iterations (parameter `1) Iterations` in `amc.inp`) to determine the actual number of photons simulated for the waveband.

    **Data Format**: The numerical values are read in free-format (list-directed). This means the numbers should be separated by spaces or commas and do not need to be aligned in fixed columns.

## Example

Here is a sample `difcol.inp` file configured for **12 wavebands**.

```
12
0.8 1.0
0.8 1.0
0.7 1.0
0.7 0.9
0.6 0.9
0.6 0.8
0.5 0.8
0.5 0.7
0.4 0.7
0.4 0.6
0.3 0.5
0.3 0.4

--- NOTES ---
This section is not read by the AOMC model.
Each line of data represents a waveband.
For each waveband, the values are:
[Direct Fraction] [Relative Intensity]
```
